### ISSUE TITLE
Broken Maven Wrapper

### ISSUE THREAD

**Issue by UgmaDevelopment** [thewaterwalker/spring-boot-ldap-react#3]
Hi,

First off, thanks for sharing this starter project.

One thing I wanted to bring to your attention is that though you have the `mvnw` and `mvnw.cmd` maven wrapper files, you seem have to left out the `.mvn` directory,

Unfortunately, that results in a broken maven wrapper. 

I think it would be resolved if you remove the `.mvn` directory from your .gitignore file, and commit the directory.

**Comment by UgmaDevelopment** [comment]
Oh, I forgot to mention, here's what made me realize the wrapper was broken: https://stackoverflow.com/questions/50104172/could-not-find-or-load-main-class-org-apache-maven-wrapper-mavenwrappermain

I got an error something like `Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain` and googled it.

**Comment by thewaterwalker** [comment]
Thanks for the update - I have included the .mvn directory
